### ISSUE TITLE
Option for asking about all items

### ISSUE THREAD

**Issue by jaskooo** [Syncano/syncano-ios#13]
_From @DigitalForms on July 9, 2015 11:13_

There should be an option to ask for all objects with given predicate, without pagination. We're going to implement it in every application anyway, so it should be in library.

_Copied from original issue: Syncano/syncano4-ios#18_

**Comment by jaskooo** [comment]
We have added enumerate function which you can use to loop for all pages of objects

**Comment by lifcio** [comment]
I think we can close it for now. 
If there's any issue with current solution, please reopen.
