### ISSUE TITLE
syncano-ios (4.1.0) Could not build Objective-C module 'syncano_ios'

### ISSUE THREAD

**Issue by fractalzombie** [Syncano/syncano-ios#131]
After update from 4.0.18 to 4.1.0 have issues:
'Mantle.h' file not found
Could not build Objective-C module 'syncano_ios'

**Comment by jaskooo** [comment]
Hello @fractalzombie. Please use new updated version 4.1.1 (it is also on cocoapods already). I have just fixed this bug :) Thanks for letting us know :+1:  Enjoy!
