### ISSUE TITLE
Error handling in - (NSString *)serializeRequest:(NSURLRequest *)request parameters:(NSDictionary *)parameters error:(NSError **)error

### ISSUE THREAD

**Issue by DigitalForms** [Syncano/syncano-ios#5]
Can we add checking if multicallParameters is nil? If not exception is thrown in next line

**Comment by lifcio** [comment]
Added. Could you check check if this is desired behaviour? Also, could you give me some info when does it happen that `parameters` is `nil`?
I checked and `- (NSString *)serializeRequest:(NSURLRequest *)request parameters:(NSDictionary *)parameters error:(NSError **)error;` is called only from `batchRequestSerializer`, which in turn is used only in 
```objc
- (id <SyncanoRequest> )getPausedBatchRequest:(NSArray *)params
                             operationManager:(AFHTTPRequestOperationManager *)operationManager
                                      success:(SyncanoBatchSuccess)success
                                      failure:(SyncanoFailure)failure
```
This methods gets params from `- (NSDictionary *)parametersDictionaryForBatchRequestParameters:(NSArray *)batchParameters` which always returns `return @{ multicallParamsKey:multicallParameters };` - so I'm just curious to know when the nil is getting set there.

**Comment by lifcio** [comment]
If there's something wrong, feel free to open the issue again.
